(Block-name: Header)
(Block-expand: 1)
(Block-enable: 1)
(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: AllDrills_simplified_allAs1mm_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Samstag, 10 September 2022 at 03:05)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 1.0)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:   12.5795 ...  154.0353  mm)
(Y range:    8.3221 ...  143.9355  mm)

(Spindle Speed: 0 RPM)
G21
G90
G17
G94


G01 F300.00

M5             
(Block-name: block)
(Block-expand: 1)
(Block-enable: 1)
(MSG, Change to Tool Dia = 1.0000 ||| Total drills for tool T1 = 172)
        
G01 F300.00
M03
G0 X94.5405 Y95.2779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 1)
(Block-enable: 1)
G0 X94.5405 Y95.2779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X94.5405 Y92.7779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X94.5405 Y90.2779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X90.7305 Y92.7779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y92.7779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y90.2779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X83.1105 Y92.7779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X79.3005 Y92.7779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X79.3005 Y90.2779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X79.3005 Y95.2779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y95.2779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X83.1105 Y82.6179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X80.5705 Y76.2679
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X83.1105 Y71.1879
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y73.7279
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y66.1079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X79.3005 Y66.1079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X80.5705 Y57.2179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X83.1105 Y52.1379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y54.6779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y47.0579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X79.3005 Y47.0579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X80.5705 Y38.1679
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X83.1105 Y33.0879
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y35.6279
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y28.0079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X79.3005 Y28.0079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X80.5705 Y19.1179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X83.1105 Y14.0379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y16.5779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y8.9579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X79.3005 Y8.9579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X98.3505 Y8.9579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X102.1605 Y14.0379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.9705 Y16.5779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X99.6205 Y19.1179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X98.3505 Y28.0079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X102.1605 Y33.0879
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.9705 Y35.6279
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X99.6205 Y38.1679
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X98.3505 Y47.0579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X102.1605 Y52.1379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.9705 Y54.6779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X99.6205 Y57.2179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X98.3505 Y66.1079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X102.1605 Y71.1879
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.9705 Y73.7279
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X99.6205 Y76.2679
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.8435 Y85.1579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y90.2379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y92.7779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y95.3179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y97.8579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y100.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y102.9379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y105.4779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y108.0179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y110.5579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y113.0979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y115.6379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y118.1779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X104.7005 Y120.7179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X86.9205 Y128.3379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X84.3805 Y128.3379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X81.8405 Y128.3379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X79.3005 Y128.3379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X40.9315 Y105.7649
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X37.3385 Y104.3619
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X34.7985 Y104.3619
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X32.2585 Y104.3619
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X29.7185 Y104.3619
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X24.8775 Y105.5109
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X30.5855 Y91.2869
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X33.1255 Y91.2869
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X35.6655 Y91.2869
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X40.9315 Y89.9649
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X24.8775 Y89.4569
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X31.0805 Y63.4479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X33.5805 Y63.4479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X36.0805 Y63.4479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X43.5705 Y63.3829
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X39.6805 Y55.9479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X43.5705 Y53.2229
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X50.0905 Y54.0429
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X60.2505 Y54.0429
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X52.6305 Y42.9979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X45.6305 Y39.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X45.6305 Y34.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X43.0105 Y34.3579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X36.1205 Y36.3579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X33.9205 Y39.1579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X31.0405 Y37.3579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X32.8505 Y34.3579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X31.0405 Y27.1979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X31.0805 Y24.8479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X36.0805 Y24.8479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X39.6805 Y17.8479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X36.0805 Y10.3479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X33.5805 Y10.3479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X31.0805 Y10.3479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X23.4205 Y10.2279
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X27.4805 Y17.8479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X23.4205 Y20.3879
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X17.0705 Y19.7529
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X6.9105 Y19.7529
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X14.5305 Y30.7979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X21.5305 Y34.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X21.5305 Y39.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X23.7605 Y39.1579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X14.5305 Y42.9979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X17.0705 Y47.0579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X16.4355 Y53.4079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X16.4355 Y63.5679
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X27.4805 Y55.9479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X31.0805 Y48.9479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X36.0805 Y48.9479
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X36.1205 Y46.5179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X52.6305 Y30.7979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X50.0905 Y26.7379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X50.7255 Y20.3879
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X50.7255 Y10.2279
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X60.2505 Y26.7379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X60.1305 Y34.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X60.1305 Y36.8979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X60.1305 Y39.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.9705 Y47.0579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X117.4005 Y47.0579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X121.2105 Y52.1379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X125.0205 Y54.6779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X118.6705 Y57.2179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X117.4005 Y66.1079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X121.2105 Y71.1879
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X125.0205 Y73.7279
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X118.6705 Y76.2679
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X125.0205 Y66.1079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X125.0205 Y47.0579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X118.6705 Y38.1679
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X121.2105 Y33.0879
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X125.0205 Y35.6279
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X125.0205 Y28.0079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X117.4005 Y28.0079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X118.6705 Y19.1179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X121.2105 Y14.0379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X125.0205 Y16.5779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X125.0205 Y8.9579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X117.4005 Y8.9579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.9705 Y8.9579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.9705 Y28.0079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X105.9705 Y66.1079
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X90.7305 Y82.6179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y90.2379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y92.7779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y95.3179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y97.8579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y100.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y102.9379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y105.4779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y108.0179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y110.5579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y113.0979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y115.6379
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y118.1779
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X127.5605 Y120.7179
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X126.7985 Y123.2579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X140.4558 Y134.6134
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X140.4558 Y0
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X7.0305 Y34.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X7.0305 Y36.8979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X7.0305 Y39.3979
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X6.9105 Y47.0579
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X0 Y0
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
G0 X0 Y134.6134
G1 Z-1.7
G1 Z0
G0 Z2
(Block-name: block)
(Block-expand: 0)
(Block-enable: 1)
M05
G0 Z0.5


